spring:
  profiles:
    name: food
    default: local

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  # ?? ??

  mail:
    host: smtp.gmail.com
    port: 587
    username: urinane1004@gmail.com
    password: rlacsixiwpesrwbz
    properties:
      mail.smtp:
        auth: true
        timeout: 5000
        starttls.enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

# ?? ??
ncp:
  storage:
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    accessKey: ncp_iam_BPASKR4csA9VuOEbWbFR
    secretKey: ncp_iam_BPKSKRDvGKCqe9qDUYffS80Bh56yG4BNc1
    localLocation: /Users/jang-yeongjae/Desktop/

cloud:
  aws:
    s3:
      bucket: contest23

# ??? API ??
naver:
  api:
    client-id: 8l4oSIo0AefMdIGsMz4m
    client-secret: BUWreWESDx

---

# Local ???? ??
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
---

# Test ???? ??
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: never
