apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest23-food-server-deployment-green
  labels:
    app: contest23-food-server
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contest23-food-server
      version: green
  template:
    metadata:
      labels:
        app: contest23-food-server
        version: green
    spec:
      containers:
        - name: contest23-food-server-container
          image: contest23-server.kr.ncr.ntruss.com/contest23-server:latest  # 그린 서버 이미지
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"