apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }
    http {
      upstream k8s-service {
        server contest23-food-server-service.default.svc.cluster.local:80;  # Kubernetes 내부 서비스로 연결
      }

      server {
        listen 80;

        location / {
          proxy_pass http://k8s-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }