apiVersion: v1
kind: Service
metadata:
  name: contest23-food-server-service-green
spec:
  selector:
    app: contest23-food-server
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP